version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: core
      POSTGRES_USER: core
      POSTGRES_PASSWORD: core
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      MISS_JANNAT_SETTINGS_DATABASES: '{"default":{"HOST":"db"}}'


volumes:
  postgresql-data:
    driver: local
