# Generated by Django 4.2.4 on 2023-09-18 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('ModelLog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='firstImage',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='first_image_operations', to='store.image'
            ),
        ),
        migrations.AddField(
            model_name='operation',
            name='secondImage',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='second_image_operations',
                to='store.image'
            ),
        ),
        migrations.AddField(
            model_name='history',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModelLog.operation'),
        ),
        migrations.AddField(
            model_name='history',
            name='resultImage',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='result_image_histories', to='store.image'
            ),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
