name: Docker Image CI

on:
  push:
    branches: [ deploy-using-docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: |
        make build
        docker tag pixel-alchemy-app rachidouhammou/pixel-alchemy:$(date +%s)

    - name: Docker Push
      run: docker push rachidouhammou/pixel-alchemy
